version: "3.9"
services:
  api:
    image: ghcr.io/bangsmackpow/gusto-pos-api:latest
    container_name: gustopos-api
    environment:
      - PORT=3000
    env_file:
      - stack.env
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/bangsmackpow/gusto-pos-frontend:latest
    container_name: gustopos-frontend
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: gustopos-db
    env_file:
      - stack.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gusto"]
      interval: 15s
      timeout: 5s
      retries: 3
