import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatMoney(
  amount: number,
  currency: string = "MXN",
  rate: number = 1,
): string {
  const converted = amount / rate;
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(converted);
}

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    tabs: "Tabs",
    menu: "Menu",
    inventory: "Inventory",
    reports: "Reports",
    settings: "Settings",
    // Auth
    login: "Log In",
    logout: "Log Out",
    switch_user: "Switch User",
    pin_prompt: "Enter your PIN",
    login_failed: "Login Failed",
    invalid_credentials: "Invalid credentials",
    connection_error: "Could not connect to server",
    welcome_back: "Welcome back",
    please_switch_staff: "Please switch staff member to begin",
    too_many_attempts: "Too Many Attempts",
    too_many_login_attempts:
      "Too many login attempts. Please try again in 15 minutes.",
    too_many_reset_attempts:
      "Too many reset attempts. Please try again in 15 minutes.",
    password_reset: "Password Reset",
    password_reset_success: "Your password has been reset. You can now log in.",
    reset_password_failed: "Reset Failed",
    reset_password_error: "Could not reset password.",
    logging_in: "Logging in...",
    switch_to_spanish: "Switch to Spanish",
    // Shifts
    active_shift: "Active Shift",
    no_active_shift: "No Active Shift",
    start_shift: "Start Shift",
    close_shift: "Close Shift",
    shift_name: "Shift Name",
    shift_date: "Shift Date",
    // Tabs
    open_tabs: "Open Tabs",
    new_tab: "New Tab",
    close_tab: "Close Tab",
    table_number: "Table # or Name",
    no_tabs: "No open tabs",
    enter_pin_first: "Enter your PIN to open a tab",
    // Orders
    add_drink: "Add Drink",
    total: "Total",
    cash: "Cash",
    card: "Card",
    payment_method: "Payment Method",
    order_added: "Item added to tab",
    order_removed: "Item removed from tab",
    tab_closed: "Tab closed and payment recorded",
    tab_opened: "Tab opened successfully",
    tip: "Tip",
    notes: "Notes",
    special_requests: "Special requests, allergies, etc...",
    promo_code: "Promo Code",
    enter_promo_code: "Enter promo code",
    apply_code: "Apply Code",
    discount: "Discount",
    code_applied: "Code applied successfully",
    // Reports & Analytics
    sales_analytics: "Sales Analytics",
    sales_by_drink: "Sales by Drink",
    sales_by_staff: "Sales by Staff",
    hourly_breakdown: "Hourly Breakdown",
    revenue: "Revenue",
    units_sold: "Units Sold",
    avg_price: "Avg Price",
    total_tabs: "Total Tabs",
    avg_ticket: "Avg Ticket",
    tips_earned: "Tips Earned",
    date_range: "Date Range",
    from_date: "From Date",
    to_date: "To Date",
    generate_report: "Generate Report",
    // Inventory Forecasting
    inventory_forecast: "Inventory Forecast",
    consumption_velocity: "Consumption Velocity",
    days_until_stockout: "Days Until Stockout",
    daily_usage: "Daily Usage",
    reorder_point: "Reorder Point",
    suggested_reorder: "Suggested Reorder",
    alert_critical: "Critical - Reorder Immediately",
    alert_low: "Low Stock - Reorder Soon",
    alert_ok: "Adequate Stock",
    forecast_period: "Forecast Period",
    analysis_period: "Analysis Period",
    critical_items: "Critical Items",
    low_items: "Low Stock Items",
    ok_items: "OK Items",
    stock_status: "Stock Status",
    usage_rate: "Usage Rate",
    days_remaining: "Days Remaining",
    consumption_summary: "Consumption Summary",
    // Inventory Audits
    inventory_audits: "Inventory Audits",
    audit_history: "Audit History",
    variance_analysis: "Variance Analysis",
    system_stock: "System Stock",
    physical_count: "Physical Count",
    audit_variance: "Variance",
    variance_percent: "Variance %",
    audit_reason: "Audit Reason",
    audited_by: "Audited By",
    audited_at: "Audited At",
    audit_notes: "Notes",
    record_audit: "Record Audit",
    physical_count_label: "Physical Count",
    underage_detection: "Underage Detection",
    overage_detection: "Overage Detection",
    high_volatility: "High Volatility",
    recent_variance: "Recent Variance",
    shrinkage_spillage: "Possible shrinkage or spillage",
    staff_overpouring: "Staff may be overpouring",
    standardize_procedures: "Standardize counting procedures",
    verify_stock_levels: "Verify stock levels",
    // Inventory

    low_stock: "Low Stock Alerts",
    low_stock_alerts: "Low Stock",
    running_sales: "Running Sales",
    all_good: "Inventory looks good",
    manage_inventory: "Manage Inventory",
    left: "left",
    ingredients: "Ingredients",
    drinks: "Drinks",
    add_item: "Add Item",
    edit_item: "Edit Item",
    new_item: "New Item",
    item_name: "Item Name",
    category: "Category",
    cost: "Cost",
    cost_per_unit: "Cost per Unit",
    cost_per_serving: "Cost per Serving",
    price: "Price",
    sell_price: "Selling Price",
    stock: "Stock",
    current_stock: "Current Stock",
    stock_units: "Units in Stock",
    stock_ml: "Volume in Stock",
    servings_remaining: "Servings Remaining",
    bottle_size: "Bottle Size",
    serving_size: "Serving Size",
    serving_size_oz: "Serving Size (oz)",
    servings_per_bottle: "Servings per Bottle",
    order_cost: "Order Cost",
    low_stock_threshold: "Low Stock Alert",
    minimum_stock: "Minimum Stock",
    profit: "Profit",
    profit_per_serving: "Profit per Serving",
    weight: "Weight",
    current_weight: "Current Weight",
    full_bottle_weight: "Full Bottle Weight",
    density_factor: "Density Factor",
    weigh_item: "Weigh Item",
    weigh_prompt: "Enter current weight on scale",
    count_history: "Count History",
    unit: "Unit",
    units: "Units",
    on_menu: "Menu",
    bottles: "bottles",
    ml: "ml",
    oz: "oz",
    grams: "g",
    can: "Can",
    bottle: "Bottle",
    units_per_case: "Units per Case",
    type: "Type",
    spirit: "Spirit",
    beer: "Beer",
    mixer: "Mixer",
    ingredient: "Ingredient",
    bulk_import: "Bulk Import",
    seed_starter: "Seed Starter Data",
    import_success: "Import Successful",
    import_failed: "Import Failed",
    file_parsed: "File Parsed",
    upload_csv: "Upload CSV",
    parse_markdown: "Parse Markdown",
    save_all: "Save All to Inventory",
    categories: "Categories",
    manage_categories: "Manage Categories",
    add_category: "Add Category",
    category_name: "Category Name",
    category_name_es: "Category Name (Spanish)",
    sort_order: "Sort Order",
    inventory_units: "Inventory Units",
    weight_unit: "Weight Unit",
    volume_unit: "Volume Unit",
    default_serving_size: "Default Serving Size",
    // Drinks
    drink_name: "Drink Name",
    drink_description: "Description",
    recipe: "Recipe",
    add_ingredient: "Add Ingredient",
    remove_ingredient: "Remove",
    amount: "Amount",
    margin: "Margin",
    markup_factor: "Markup Factor",
    actual_price: "Selling Price",
    suggested_price: "Suggested Price",
    estimated_cost: "Estimated Cost",
    is_available: "Available",
    drink_saved: "Drink saved",
    drink_category: "Category",
    cocktail: "Cocktail",
    shot: "Shot",
    wine: "Wine",
    non_alcoholic: "Non-Alcoholic",
    // Settings
    branding: "Branding",
    bar_name: "Bar Name",
    bar_icon: "Bar Icon",
    disaster_recovery: "Disaster Recovery",
    litestream: "Litestream (Cloud Sync)",
    usb_backup: "USB Backup",
    settings_saved: "Settings saved successfully",
    settings_error: "Failed to save settings",
    // Staff
    staff_mgmt: "Staff Management",
    add_staff: "Add Staff Member",
    first_name: "First Name",
    last_name: "Last Name",
    email: "Email",
    password: "Password",
    pin: "PIN",
    role: "Role",
    active: "Active",
    inactive: "Inactive",
    archived: "Archived",
    unarchive: "Unarchive",
    staff_saved: "Staff member saved",
    // Rushes
    rushes: "Rush Events",
    pv_rushes: "Puerto Vallarta Rushes",
    no_events_24h: "No events scheduled for the next 24 hours.",
    manage_rushes: "Manage Rushes",
    add_event: "Add Event",
    event_title: "Title",
    event_type: "Type",
    event_impact: "Impact",
    impact: "impact",
    start_time: "Start Time",
    end_time: "End Time",
    description: "Description",
    cruise: "Cruise",
    festival: "Festival",
    music: "Music",
    event: "Event",
    low: "Low",
    medium: "Medium",
    high: "High",
    // Reports
    shift_summary: "Shift Summary",
    top_sellers: "Top Sellers",
    inventory_used: "Inventory Used",
    sales: "Sales",
    sales_by_category: "Sales by Category",
    end_of_night: "End of Night Report",
    // Common
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    confirm: "Confirm",
    search: "Search",
    loading: "Loading...",
    no_results: "No results found",
    error: "Error",
    success: "Success",
    warning: "Warning",
    yes: "Yes",
    no: "No",
    order: "Order?",
    actions: "Actions",
    // Exchange rates
    exchange_rates: "Exchange Rates",
    usd_to_mxn: "USD to MXN",
    cad_to_mxn: "CAD to MXN",
    // Notifications
    notifications: "Notifications",
    // Drink categories for inventory
    tequila: "Tequila",
    mezcal: "Mezcal",
    vodka: "Vodka",
    gin: "Gin",
    whiskey: "Whiskey",
    rum: "Rum/Ron",
    misc_liquor: "Misc Liquor",
    cerveza_nacional: "Cerveza Nacional",
    cerveza_importada: "Cerveza Importada",
    caguamos: "Caguamos",
    cerveza_misc: "Cerveza Misc",
    cerveza_cero: "Cerveza Cero",
    mixers: "Mixers",
    // Dashboard close summary
    close_shift_summary: "Close Shift Summary",
    open_tabs_label: "Open Tabs",
    total_sales_open_tabs: "Total Sales (open tabs)",
    low_stock_items: "Low Stock Items",
    open_tabs_warning:
      "Warning: You have {count} open tab{plural}. These will remain open after the shift closes.",
    confirm_close: "Confirm Close",
    closing: "Closing...",
    force_close: "Force close with open tabs",
    // Tabs page
    manage_tables_customers: "Manage open tables and customers",
    no_open_tabs_msg: "No open tabs",
    search_tabs: "Search tabs...",
    table_or_name_placeholder: "Table # or Name",
    add: "Add",
    delete_tab_confirm:
      "Are you sure you want to delete this tab? This action cannot be undone.",
    opened_x_ago: "Opened {time} ago",
    loading_tabs: "Loading tabs...",
    sort_by: "Sort by",
    opened_time: "Opened Time",
    sort_name: "Name",
    sort_total: "Total",
    // Inventory sidebar
    all_items: "All Items",
    items_count: "{count} items",
    low_stock_count: "{count} low stock",
    search_inventory: "Search inventory",
    types_label: "Types",
    all_items_header: "All Items",
    items_count_header: "{count} items",
    spirits: "Spirits",
    merch: "Merch",
    misc: "Misc",
    // Inventory form fields
    spanish_name: "Spanish Name",
    subtype: "Subtype",
    base_unit: "Base Unit",
    base_unit_amount: "Base Unit Amount",
    pour_size: "Pour Size (oz)",
    pour_size_label: "Pour Size",
    low_stock_alert_label: "Low Stock Alert",
    on_menu_label: "Show on Menu",
    bottle_size_ml: "Bottle Size (ml)",
    glass_weight: "Container Weight",
    density_label: "Density",
    full_bottle_weight_label: "Full Bottle Weight (g)",
    current_bottle_weight: "Active Bottle Weight (g)",
    calculate: "Calculate",
    weigh_bottle: "Weigh Bottle",
    remaining_pours: "Remaining Pours",
    used_pours: "Used Pours",
    full_bottle_count: "Full Bottle Count",
    total_inventory: "Total Inventory",
    full_bottles: "full bottles",
    variance: "Variance",
    // Drinks page
    search_drinks: "Search drinks...",
    no_drinks_found: 'No drinks found for "{search}"',
    edit_drink: "Edit Drink",
    new_drink: "New Drink",
    name_label: "Name",
    actual_price_label: "Actual Selling Price (MXN)",
    recipe_ingredients: "Recipe & Ingredients",
    select_subtype: "Select subtype...",
    select_ingredient: "Select ingredient...",
    pour_amount: "Pour Amount (oz)",
    estimated_cost_label: "Estimated Cost:",
    markup_label: "Markup (x{factor}):",
    delete_drink: "Delete Drink",
    delete_drink_confirm:
      'Are you sure you want to delete "{name}"? This action cannot be undone.',
    price_greater_zero: "Price must be greater than 0",
    // Settings
    pin_lock_timeout: "PIN Lock Timeout (minutes)",
    pin_lock_timeout_desc:
      "Automatically lock the POS after this many minutes of inactivity",
    branding_config: "Branding & Configuration",
    backups_dr: "Backups & Disaster Recovery",
    litestream_desc:
      "Stream SQLite WAL to S3-compatible storage for real-time backup",
    enable_litestream: "Enable Litestream",
    usb_backup_desc:
      "Periodic backup to mounted USB drive for offline recovery",
    enable_usb_backup: "Enable USB Backup",
    save_config: "Save Configuration",
    save_backup: "Save Backup Settings",
    add_staff_btn: "Add Staff",
    data_management: "Data Management",
    import_ingredients: "Import Ingredients",
    import_recipes: "Import Recipes",
    seed_library: "Seed Library",
    load_starter: "Load starter data",
    reset_database: "Reset Database",
    delete_all_data: "Delete all data",
    reset_db_confirm:
      "Are you sure you want to reset the entire database? This will delete ALL data including drinks, inventory, tabs, shifts, and settings. This cannot be undone.",
    reset_db_title: "Reset Database",
    resetting: "Resetting...",
    rush_events: "Rush Events",
    schedule_rush: "Schedule Rush",
    schedule_a_rush: "Schedule a Rush",
    event_title_label: "Event Title",
    type_label: "Type",
    impact_label: "Impact",
    start_time_label: "Start Time",
    schedule_event: "Schedule Event",
    edit_staff: "Edit Staff",
    new_staff: "New Staff",
    email_required: "Email (Required for Login)",
    account_password: "Account Password",
    leave_blank_keep: "Leave blank to keep current",
    set_login_password: "Set login password",
    // PIN lock
    pos_locked: "POS is Locked",
    enter_pin_unlock: "Enter your PIN to unlock",
    // Common
    manage_drinks: "Manage drinks, recipes and pricing",
    configure_pos: "Configure your POS system",
    other: "Other",
    admin: "Admin",
    employee: "Employee",
    manager: "Manager",
    head_bartender: "Head Bartender",
    bartender: "Bartender",
    server: "Server",
    cruise_ship: "Cruise Ship",
    live_music: "Live Music",
    reset: "Reset",
    apply: "Apply",
    preview: "Preview",
    map_columns: "Map Columns",
    upload_csv_file: "Upload CSV File",
    rows_ready: "rows ready to import",
    import: "Import",
    close: "Close",
    back: "Back",
    next: "Next",
    step: "Step",
    of: "of",
    required: "Required",
    optional: "Optional",
    none: "None",
    all: "All",
    filter: "Filter",
    clear: "Clear",
    apply_filters: "Apply Filters",
    on_menu_filter: "On Menu",
    // Tax Configuration (Phase 4.1)
    tax_rates: "Tax Rates",
    tax_configuration: "Tax Configuration",
    tax_category: "Tax Category",
    tax_rate: "Tax Rate",
    tax_rate_percent: "Rate (%)",
    standard_rate: "Standard Rate",
    reduced_rate: "Reduced Rate",
    food_tax: "Food Tax",
    spirits_tax: "Spirits Tax",
    beer_tax: "Beer Tax",
    non_taxable: "Non-Taxable",
    tax_calculation: "Tax Calculation",
    subtotal: "Subtotal",
    tax_amount: "Tax Amount",
    total_with_tax: "Total with Tax",
    update_tax_rate: "Update Tax Rate",
    tax_summary: "Tax Summary",
    tax_collected: "Tax Collected",
    tax_by_category: "Tax by Category",
    effective_tax_rate: "Effective Tax Rate",
    // Staff Shifts (Phase 4.4)
    staff_shifts: "Staff Shifts",
    clock_in: "Clock In",
    clock_out: "Clock Out",
    clock_in_success: "Clocked in successfully",
    clock_out_success: "Clocked out successfully",
    already_clocked_in: "Already clocked in",
    not_clocked_in: "Not clocked in",
    clock_in_time: "Clock In Time",
    clock_out_time: "Clock Out Time",
    hours_worked: "Hours Worked",
    break_time: "Break Time",
    break_start: "Break Start",
    break_end: "Break End",
    break_minutes: "Break Minutes",
    // Staff Performance
    staff_performance: "Staff Performance",
    performance_metrics: "Performance Metrics",
    top_performer: "Top Performer",
    performance_summary: "Performance Summary",
    revenue_generated: "Revenue Generated",
    total_orders_staff: "Total Orders",
    average_order_value_staff: "Average Order Value",
    orders_per_hour: "Orders per Hour",
    revenue_per_hour: "Revenue per Hour",
    tips_percentage: "Tips Percentage",
    customer_count_staff: "Customer Count",
    total_tabs_staff: "Total Tabs",
    average_tab_value: "Average Tab Value",
    staff_ranking: "Staff Ranking",
    performance_score: "Performance Score",
    // Split Bill
    split_bill: "Split Bill",
    add_payment: "Add Payment",
    remove_payment: "Remove",
    payment_total: "Payment Total",
    remaining: "Remaining",
    split_tip: "Tip",
    split_method: "Method",
    split_amount: "Amount",
    even_split: "Split Evenly",
    payments_mismatch: "Payments must equal the tab total",
  },
  es: {
    // Navigation
    dashboard: "Panel",
    tabs: "Cuentas",
    menu: "Menú",
    inventory: "Inventario",
    reports: "Reportes",
    settings: "Ajustes",
    // Auth
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    switch_user: "Cambiar Usuario",
    pin_prompt: "Ingrese su PIN",
    login_failed: "Error de Inicio de Sesión",
    invalid_credentials: "Credenciales inválidas",
    connection_error: "No se pudo conectar al servidor",
    welcome_back: "Bienvenido de vuelta",
    please_switch_staff: "Cambie de miembro de personal para comenzar",
    too_many_attempts: "Demasiados Intentos",
    too_many_login_attempts:
      "Demasiados intentos de inicio de sesión. Por favor, intente más tarde en 15 minutos.",
    too_many_reset_attempts:
      "Demasiados intentos de reinicio. Por favor, intente más tarde en 15 minutos.",
    password_reset: "Reinicio de Contraseña",
    password_reset_success:
      "Su contraseña ha sido reiniciada. Ahora puede iniciar sesión.",
    reset_password_failed: "Error de Reinicio",
    reset_password_error: "No se pudo reiniciar la contraseña.",
    logging_in: "Iniciando sesión...",
    switch_to_spanish: "Cambiar a Español",
    // Shifts
    active_shift: "Turno Activo",
    no_active_shift: "Ningún Turno Activo",
    start_shift: "Iniciar Turno",
    close_shift: "Cerrar Turno",
    shift_name: "Nombre del Turno",
    shift_date: "Fecha del Turno",
    // Tabs
    open_tabs: "Cuentas Abiertas",
    new_tab: "Nueva Cuenta",
    close_tab: "Cerrar Cuenta",
    table_number: "Mesa # o Nombre",
    no_tabs: "No hay cuentas abiertas",
    enter_pin_first: "Ingrese su PIN para abrir una cuenta",
    // Orders
    add_drink: "Agregar Bebida",
    total: "Total",
    cash: "Efectivo",
    card: "Tarjeta",
    payment_method: "Método de Pago",
    order_added: "Artículo agregado a la cuenta",
    order_removed: "Artículo eliminado de la cuenta",
    tab_closed: "Cuenta cerrada y pago registrado",
    tab_opened: "Cuenta abierta exitosamente",
    tip: "Propina",
    notes: "Notas",
    special_requests: "Solicitudes especiales, alergias, etc...",
    promo_code: "Código Promocional",
    enter_promo_code: "Ingrese código promocional",
    apply_code: "Aplicar Código",
    discount: "Descuento",
    code_applied: "Código aplicado exitosamente",
    // Reports & Analytics
    sales_analytics: "Análisis de Ventas",
    sales_by_drink: "Ventas por Bebida",
    sales_by_staff: "Ventas por Personal",
    hourly_breakdown: "Desglose por Hora",
    revenue: "Ingresos",
    units_sold: "Unidades Vendidas",
    avg_price: "Precio Promedio",
    total_tabs: "Total de Cuentas",
    avg_ticket: "Ticket Promedio",
    tips_earned: "Propinas Ganadas",
    date_range: "Rango de Fechas",
    from_date: "Desde",
    to_date: "Hasta",
    generate_report: "Generar Reporte",
    // Inventory Forecasting
    inventory_forecast: "Pronóstico de Inventario",
    consumption_velocity: "Velocidad de Consumo",
    days_until_stockout: "Días Hasta Falta de Stock",
    daily_usage: "Uso Diario",
    reorder_point: "Punto de Reorden",
    suggested_reorder: "Reorden Sugerido",
    alert_critical: "Crítico - Reordenar Inmediatamente",
    alert_low: "Stock Bajo - Reordenar Pronto",
    alert_ok: "Stock Adecuado",
    forecast_period: "Período de Pronóstico",
    analysis_period: "Período de Análisis",
    critical_items: "Artículos Críticos",
    low_items: "Artículos con Stock Bajo",
    ok_items: "Artículos OK",
    stock_status: "Estado del Stock",
    usage_rate: "Tasa de Uso",
    days_remaining: "Días Restantes",
    consumption_summary: "Resumen de Consumo",
    // Inventory Audits
    inventory_audits: "Auditorías de Inventario",
    audit_history: "Historial de Auditorías",
    variance_analysis: "Análisis de Varianza",
    system_stock: "Stock en Sistema",
    physical_count: "Conteo Físico",
    audit_variance: "Varianza",
    variance_percent: "Varianza %",
    audit_reason: "Razón de Auditoría",
    audited_by: "Auditado Por",
    audited_at: "Auditado En",
    audit_notes: "Notas",
    record_audit: "Registrar Auditoría",
    physical_count_label: "Conteo Físico",
    underage_detection: "Detección de Falta",
    overage_detection: "Detección de Exceso",
    high_volatility: "Alta Volatilidad",
    recent_variance: "Varianza Reciente",
    shrinkage_spillage: "Posible merma o derrame",
    staff_overpouring: "Personal puede estar vertiendo en exceso",
    standardize_procedures: "Estandarizar procedimientos de conteo",
    verify_stock_levels: "Verificar niveles de stock",
    // Inventory

    low_stock: "Alertas de Stock Bajo",
    low_stock_alerts: "Stock Bajo",
    running_sales: "Ventas en Curso",
    manage_inventory: "Administrar Inventario",
    left: "restante",
    all_good: "Inventario en orden",
    ingredients: "Ingredientes",
    drinks: "Bebidas",
    add_item: "Agregar Artículo",
    edit_item: "Editar Artículo",
    new_item: "Nuevo Artículo",
    item_name: "Nombre del Artículo",
    category: "Categoría",
    cost: "Costo",
    cost_per_unit: "Costo por Unidad",
    cost_per_serving: "Costo por Porción",
    price: "Precio",
    sell_price: "Precio de Venta",
    stock: "Inventario",
    current_stock: "Inventario Actual",
    stock_units: "Unidades en Stock",
    stock_ml: "Volumen en Stock",
    servings_remaining: "Porciones Restantes",
    bottle_size: "Tamaño de Botella",
    serving_size: "Tamaño de Porción",
    serving_size_oz: "Tamaño de Porción (oz)",
    servings_per_bottle: "Porciones por Botella",
    order_cost: "Costo de Pedido",
    low_stock_threshold: "Alerta de Stock Bajo",
    minimum_stock: "Stock Mínimo",
    profit: "Ganancia",
    profit_per_serving: "Ganancia por Porción",
    weight: "Peso",
    current_weight: "Peso Actual",
    full_bottle_weight: "Peso de Botella Llena",
    density_factor: "Factor de Densidad",
    weigh_item: "Pesar Artículo",
    weigh_prompt: "Ingrese el peso actual en la báscula",
    count_history: "Historial de Conteo",
    unit: "Unidad",
    units: "Unidades",
    on_menu: "Menú",
    bottles: "botellas",
    ml: "ml",
    oz: "oz",
    grams: "g",
    can: "Lata",
    bottle: "Botella",
    units_per_case: "Unidades por Caja",
    type: "Tipo",
    spirit: "Licor",
    beer: "Cerveza",
    mixer: "Mezclador",
    ingredient: "Ingrediente",
    bulk_import: "Importación Masiva",
    seed_starter: "Datos Iniciales",
    import_success: "Importación Exitosa",
    import_failed: "Importación Fallida",
    file_parsed: "Archivo Procesado",
    upload_csv: "Subir CSV",
    parse_markdown: "Procesar Markdown",
    save_all: "Guardar Todo al Inventario",
    categories: "Categorías",
    manage_categories: "Administrar Categorías",
    add_category: "Agregar Categoría",
    category_name: "Nombre de Categoría",
    category_name_es: "Nombre de Categoría (Español)",
    sort_order: "Orden",
    inventory_units: "Unidades de Inventario",
    weight_unit: "Unidad de Peso",
    volume_unit: "Unidad de Volumen",
    default_serving_size: "Tamaño de Porción Predeterminado",
    // Drinks
    drink_name: "Nombre de la Bebida",
    drink_description: "Descripción",
    recipe: "Receta",
    add_ingredient: "Agregar Ingrediente",
    remove_ingredient: "Eliminar",
    amount: "Cantidad",
    margin: "Margen",
    markup_factor: "Factor de Markup",
    actual_price: "Precio de Venta",
    suggested_price: "Precio Sugerido",
    estimated_cost: "Costo Estimado",
    is_available: "Disponible",
    drink_saved: "Bebida guardada",
    drink_category: "Categoría",
    cocktail: "Cóctel",
    shot: "Shot",
    wine: "Vino",
    non_alcoholic: "Sin Alcohol",
    // Settings
    branding: "Marca",
    bar_name: "Nombre del Bar",
    bar_icon: "Ícono del Bar",
    disaster_recovery: "Recuperación de Desastres",
    litestream: "Litestream (Sync en la Nube)",
    usb_backup: "Respaldo USB",
    settings_saved: "Ajustes guardados exitosamente",
    settings_error: "Error al guardar ajustes",
    // Staff
    staff_mgmt: "Gestión de Personal",
    add_staff: "Agregar Personal",
    first_name: "Nombre",
    last_name: "Apellido",
    email: "Correo Electrónico",
    password: "Contraseña",
    pin: "NIP",
    role: "Rol",
    active: "Activo",
    inactive: "Inactivo",
    archived: "Archivado",
    unarchive: "Desarchivar",
    staff_saved: "Personal guardado",
    // Rushes
    rushes: "Eventos de Afluencia",
    pv_rushes: "Eventos en Puerto Vallarta",
    no_events_24h: "No hay eventos programados para las próximas 24 horas.",
    manage_rushes: "Administrar Eventos",
    add_event: "Agregar Evento",
    event_title: "Título",
    event_type: "Tipo",
    event_impact: "Impacto",
    impact: "impacto",
    start_time: "Hora de Inicio",
    end_time: "Hora de Fin",
    description: "Descripción",
    cruise: "Crucero",
    festival: "Festival",
    music: "Música",
    event: "Evento",
    low: "Bajo",
    medium: "Medio",
    high: "Alto",
    // Reports
    shift_summary: "Resumen del Turno",
    top_sellers: "Más Vendidos",
    inventory_used: "Inventario Utilizado",
    sales: "Ventas",
    sales_by_category: "Ventas por Categoría",
    end_of_night: "Reporte de Fin de Noche",
    // Common
    save: "Guardar",
    edit: "Editar",
    delete: "Eliminar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    search: "Buscar",
    loading: "Cargando...",
    no_results: "No se encontraron resultados",
    error: "Error",
    success: "Éxito",
    warning: "Advertencia",
    yes: "Sí",
    no: "No",
    order: "¿Pedir?",
    actions: "Acciones",
    // Exchange rates
    exchange_rates: "Tipos de Cambio",
    usd_to_mxn: "USD a MXN",
    cad_to_mxn: "CAD a MXN",
    // Notifications
    notifications: "Notificaciones",
    // Drink categories for inventory
    tequila: "Tequila",
    mezcal: "Mezcal",
    vodka: "Vodka",
    gin: "Gin",
    whiskey: "Whiskey",
    rum: "Ron",
    misc_liquor: "Licores Varios",
    cerveza_nacional: "Cerveza Nacional",
    cerveza_importada: "Cerveza Importada",
    caguamos: "Caguamos",
    cerveza_misc: "Cerveza Misc",
    cerveza_cero: "Cerveza Cero",
    mixers: "Mezcladores",
    // Dashboard close summary
    close_shift_summary: "Resumen de Cierre de Turno",
    open_tabs_label: "Cuentas Abiertas",
    total_sales_open_tabs: "Ventas Totales (cuentas abiertas)",
    low_stock_items: "Artículos con Stock Bajo",
    open_tabs_warning:
      "Advertencia: Tienes {count} cuenta{plural} abierta{plural}. Permanecerán abiertas después de cerrar el turno.",
    confirm_close: "Confirmar Cierre",
    closing: "Cerrando...",
    force_close: "Forzar cierre con cuentas abiertas",
    // Tabs page
    manage_tables_customers: "Administrar mesas y clientes abiertos",
    no_open_tabs_msg: "No hay cuentas abiertas",
    search_tabs: "Buscar cuentas...",
    table_or_name_placeholder: "Mesa # o Nombre",
    add: "Agregar",
    delete_tab_confirm:
      "¿Estás seguro de que quieres eliminar esta cuenta? Esta acción no se puede deshacer.",
    opened_x_ago: "Abierta hace {time}",
    loading_tabs: "Cargando cuentas...",
    sort_by: "Ordenar por",
    opened_time: "Hora de Apertura",
    sort_name: "Nombre",
    sort_total: "Total",
    // Inventory sidebar
    all_items: "Todos los Artículos",
    items_count: "{count} artículos",
    low_stock_count: "{count} stock bajo",
    search_inventory: "Buscar inventario",
    types_label: "Tipos",
    all_items_header: "Todos los Artículos",
    items_count_header: "{count} artículos",
    spirits: "Licores",
    merch: "Mercancía",
    misc: "Varios",
    // Inventory form fields
    spanish_name: "Nombre en Español",
    subtype: "Subtipo",
    base_unit: "Unidad Base",
    base_unit_amount: "Cantidad Unidad Base",
    pour_size: "Tamaño de Vertido (oz)",
    pour_size_label: "Tamaño de Vertido",
    low_stock_alert_label: "Alerta de Stock Bajo",
    on_menu_label: "Mostrar en Menú",
    bottle_size_ml: "Tamaño de Botella (ml)",
    glass_weight: "Peso del Contenedor",
    density_label: "Densidad",
    full_bottle_weight_label: "Peso Botella Llena (g)",
    current_bottle_weight: "Peso Botella Actual (g)",
    calculate: "Calcular",
    weigh_bottle: "Pesar Botella",
    remaining_pours: "Vertidos Restantes",
    used_pours: "Vertidos Usados",
    full_bottle_count: "Cantidad Botellas Llenas",
    total_inventory: "Inventario Total",
    full_bottles: "botellas llenas",
    variance: "Varianza",
    // Drinks page
    search_drinks: "Buscar bebidas...",
    no_drinks_found: 'No se encontraron bebidas para "{search}"',
    edit_drink: "Editar Bebida",
    new_drink: "Nueva Bebida",
    name_label: "Nombre",
    actual_price_label: "Precio de Venta Real (MXN)",
    recipe_ingredients: "Receta e Ingredientes",
    select_subtype: "Seleccionar subtipo...",
    select_ingredient: "Seleccionar ingrediente...",
    pour_amount: "Cantidad de Vertido (oz)",
    estimated_cost_label: "Costo Estimado:",
    markup_label: "Markup (x{factor}):",
    delete_drink: "Eliminar Bebida",
    delete_drink_confirm:
      '¿Estás seguro de que quieres eliminar "{name}"? Esta acción no se puede deshacer.',
    price_greater_zero: "El precio debe ser mayor a 0",
    // Settings
    pin_lock_timeout: "Bloqueo de PIN (minutos)",
    pin_lock_timeout_desc:
      "Bloquear automáticamente el POS después de estos minutos de inactividad",
    branding_config: "Marca y Configuración",
    backups_dr: "Respaldos y Recuperación de Desastres",
    litestream_desc:
      "Transmitir SQLite WAL a almacenamiento compatible con S3 para respaldo en tiempo real",
    enable_litestream: "Habilitar Litestream",
    usb_backup_desc:
      "Respaldo periódico a unidad USB montada para recuperación sin conexión",
    enable_usb_backup: "Habilitar Respaldo USB",
    save_config: "Guardar Configuración",
    save_backup: "Guardar Respaldo",
    staff_management: "Gestión de Personal",
    add_staff_btn: "Agregar Personal",
    data_management: "Gestión de Datos",
    import_ingredients: "Importar Ingredientes",
    import_recipes: "Importar Recetas",
    seed_library: "Biblioteca de Datos",
    load_starter: "Cargar datos iniciales",
    reset_database: "Reiniciar Base de Datos",
    delete_all_data: "Eliminar todos los datos",
    reset_db_confirm:
      "¿Estás seguro de que quieres reiniciar toda la base de datos? Esto eliminará TODOS los datos incluyendo bebidas, inventario, cuentas, turnos y configuración. Esto no se puede deshacer.",
    reset_db_title: "Reiniciar Base de Datos",
    resetting: "Reiniciando...",
    rush_events: "Eventos de Afluencia",
    schedule_rush: "Programar Evento",
    schedule_a_rush: "Programar un Evento",
    event_title_label: "Título del Evento",
    type_label: "Tipo",
    impact_label: "Impacto",
    start_time_label: "Hora de Inicio",
    schedule_event: "Programar Evento",
    edit_staff: "Editar Personal",
    new_staff: "Nuevo Personal",
    email_required: "Correo (Requerido para Iniciar Sesión)",
    account_password: "Contraseña de Cuenta",
    leave_blank_keep: "Dejar en blanco para mantener la actual",
    set_login_password: "Establecer contraseña de inicio de sesión",
    // PIN lock
    pos_locked: "El POS está Bloqueado",
    enter_pin_unlock: "Ingresa tu PIN para desbloquear",
    // Common
    manage_drinks: "Administrar bebidas, recetas y precios",
    configure_pos: "Configura tu sistema POS",
    other: "Otro",
    admin: "Admin",
    employee: "Empleado",
    manager: "Gerente",
    head_bartender: "Barman Principal",
    bartender: "Barman",
    server: "Mesero",
    cruise_ship: "Crucero",
    live_music: "Música en Vivo",
    reset: "Reiniciar",
    apply: "Aplicar",
    preview: "Vista Previa",
    map_columns: "Mapear Columnas",
    upload_csv_file: "Subir Archivo CSV",
    rows_ready: "filas listas para importar",
    import: "Importar",
    close: "Cerrar",
    back: "Atrás",
    next: "Siguiente",
    step: "Paso",
    of: "de",
    required: "Requerido",
    optional: "Opcional",
    none: "Ninguno",
    all: "Todos",
    filter: "Filtrar",
    clear: "Limpiar",
    apply_filters: "Aplicar Filtros",
    on_menu_filter: "En Menú",
    // Tax Configuration (Phase 4.1)
    tax_rates: "Tasas de Impuesto",
    tax_configuration: "Configuración de Impuestos",
    tax_category: "Categoría de Impuesto",
    tax_rate: "Tasa de Impuesto",
    tax_rate_percent: "Tasa (%)",
    standard_rate: "Tasa Estándar",
    reduced_rate: "Tasa Reducida",
    food_tax: "Impuesto Alimentos",
    spirits_tax: "Impuesto Espirituosos",
    beer_tax: "Impuesto Cerveza",
    non_taxable: "Sin Impuesto",
    tax_calculation: "Cálculo de Impuesto",
    subtotal: "Subtotal",
    tax_amount: "Cantidad de Impuesto",
    total_with_tax: "Total con Impuesto",
    update_tax_rate: "Actualizar Tasa de Impuesto",
    tax_summary: "Resumen de Impuestos",
    tax_collected: "Impuesto Recaudado",
    tax_by_category: "Impuesto por Categoría",
    effective_tax_rate: "Tasa Efectiva",
    // Staff Shifts (Phase 4.4)
    staff_shifts: "Turnos de Personal",
    clock_in: "Registrar Entrada",
    clock_out: "Registrar Salida",
    clock_in_success: "Entrada registrada exitosamente",
    clock_out_success: "Salida registrada exitosamente",
    already_clocked_in: "Ya está registrado",
    not_clocked_in: "No está registrado",
    clock_in_time: "Hora de Entrada",
    clock_out_time: "Hora de Salida",
    hours_worked: "Horas Trabajadas",
    break_time: "Tiempo de Descanso",
    break_start: "Inicio de Descanso",
    break_end: "Fin de Descanso",
    break_minutes: "Minutos de Descanso",
    // Staff Performance
    staff_performance: "Desempeño del Personal",
    performance_metrics: "Métricas de Desempeño",
    top_performer: "Mejor Desempeño",
    performance_summary: "Resumen de Desempeño",
    revenue_generated: "Ingresos Generados",
    total_orders_staff: "Total de Órdenes",
    average_order_value_staff: "Valor Promedio de Orden",
    orders_per_hour: "Órdenes por Hora",
    revenue_per_hour: "Ingresos por Hora",
    tips_percentage: "Porcentaje de Propinas",
    customer_count_staff: "Conteo de Clientes",
    total_tabs_staff: "Total de Cuentas",
    average_tab_value: "Valor Promedio de Cuenta",
    staff_ranking: "Ranking de Personal",
    performance_score: "Puntuación de Desempeño",
    // Split Bill
    split_bill: "Dividir Cuenta",
    add_payment: "Agregar Pago",
    remove_payment: "Eliminar",
    payment_total: "Total de Pagos",
    remaining: "Restante",
    split_tip: "Propina",
    split_method: "Método",
    split_amount: "Cantidad",
    even_split: "Dividir Equitativamente",
    payments_mismatch: "Los pagos deben igualar el total de la cuenta",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function getTranslation(key: string, lang: "en" | "es"): string {
  const k = key as TranslationKey;
  if (translations[lang] && translations[lang][k]) {
    return translations[lang][k];
  }
  return key;
}
