-- Migration 0001: Hash existing plaintext PINs
-- 
-- IMPLEMENTATION:
-- The PIN hashing system uses an auto-migration approach:
-- 
-- 1. NEW PINS: Automatically hashed via bcrypt (cost: 10) when users are created/updated
--    - Location: api-server/src/routes/users.ts
--    - Function: hashPin() uses bcrypt.hash(pin, 10)
--    - Applied on: POST /api/users and PATCH /api/users/:id
--
-- 2. EXISTING PLAINTEXT PINS: Auto-migrated on first login via backward-compatible auth
--    - Location: api-server/src/routes/pin-login.ts  
--    - Detection: Checks if PIN starts with "$2" (bcrypt hash prefix)
--    - If plaintext: Compares directly, then upgrades hash in database on success
--    - Auto-upgrade: Happens transparently, user sees no difference
--
-- 3. STORAGE: PIN column remains TEXT and stores bcrypt hashes ($2a$10$...)
--    - Hash format: $2a$10$... (10 = cost factor)
--    - Security: PINs cannot be read or brute-forced from database dump
--
-- VALIDATION:
-- - PIN format: 4 digits only (/^[0-9]{4}$/)
-- - Reject patterns: All same digit sequences (0000, 1111, 2222, etc.)
-- - Applied: Both at creation time and login attempt
--
-- RATE LIMITING:
-- - PIN login: 5 attempts per 15 minutes per (email + IP)
-- - Admin login: 5 attempts per 15 minutes per IP
-- - Headers: RateLimit-Limit, RateLimit-Remaining, RateLimit-Reset

